blank_issues_enabled: false
contact_links:
  - name: 🚑 Self-Hosted help and support
    url: https://www.getmangoo.com/docs
    about: Please use the self-hosted community forum for any self-hosted issues and questions
  - name: 💡 Feature requests and ideas
    url: https://www.getmangoo.com/docs
    about: Please vote for and post new feature ideas in the community forum
  - name: 📖 Documentation
    url: https://www.getmangoo.com/docs
    about: A great place to find instructions and answers on how to get the most out of your Plausible experience
